#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -config ~/.config/rofi/config.rasi -xoffset -802 -yoffset -394"
uptime=$(uptime -p | sed -e 's/up //g')
usedcpu=$(/home/jaomaloy/development/utils/tools/usedcpu)
usedram=$(/home/jaomaloy/development/utils/tools/usedram -p)

# Options
shutdown="Shutdown"
reboot="Reboot"
lock="Lock"
suspend="Suspend"
logout="Logout"

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"
# 祥  $uptime $usedcpu \n$usedram%
chosen="$(echo -e "$options" | $rofi_command -p "" -dmenu -selected-row 2 -m -1)"
case $chosen in
    $shutdown)
        promptmenu --yes-command "systemctl poweroff" --query "Shutdown?"
        ;;
    $reboot)
        promptmenu --yes-command "systemctl reboot" --query "Reboot?"
        ;;
    $lock)
        multilockscreen --lock
        ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        openbox --exit
        ;;
esac

